version: '3'
services:
    starterapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: starterapp
        ports:
            - 3000:7000
        volumes:
            - .env/:/app/.env
