version: '3'
services:
    starterapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: starterapp
        depends_on:
            - postgres
        ports:
            - 3000:3000
        volumes:
            - .env/:/app/.env
        networks:
            - starterappnet

    postgres:
        image: postgres:12
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./src/database/sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: admin
            POSTGRES_DB: starter_app
        networks:
            - starterappnet

networks:
    starterappnet:
        driver: bridge
